version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
parameters:
 # システム
  system:
    type: string
    default: "none"
workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/sub_config.yml
          mapping: |
            ## リリース ##
            rel/jp/.*                        test-ci-release                                        true
            rel/us/.*                        test-ci-release                                        true
