version: 2.1

setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  # say-hello-workflow:
  #   jobs:
  #     - say-hello
  # setup:
  #   jobs:
  #     - setup
  test-jp-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/sub_config.yml
          mapping: |
            jp/.*      test-ci-release_jp         true
            us/.*      test-ci-release_us         true
