version: 2.1
orbs:
  python: circleci/python@2.1.1
  path-filtering: circleci/path-filtering@0.0.2

## define 
parameters:
  test-ci-release_us:
    type: boolean
    default: false
  test-ci-release_jp:
    type: boolean
    default: false

executors:
  default:
    docker:
      - image: cimg/python:3.11
    environment:
      TZ: "JST-9"

jobs:
  execute_shell_script:
    parameters:
      rel:
        type: string
        default: ""
      file:
        type: string
        default: ""
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: execute_script
          command: |
            set -x
            echo Hello, World!
            rel="<< parameters.rel >>"
            file="<< parameters.file >>"
            echo rel=${rel} file=${file}
            pwd
            env
            uname -a
            lsb_release -a
            id
            git branch
            git status
            which pip 
            which pip3
            # sudo apt-get update -y
            # sudo apt-get install python3 python3-pip python3-setuptools
            # sudo apt-get install python3 python3-pip
            # sudo apt-get install -y python3-setuptools python3-pip
            pip3 install ruamel.yaml
            python3 --version
            # sudo apt-get install python3-pip
            pip3 list

  execute_update_script:
    executor:
      name: default
    steps:
      - run:
          name: execute_update_script
          command: |
            set -x
            echo update script
            pwd
            env
            uname -a
            lsb_release -a
            pip3 list

  #
  no_job_execution:
    docker:
      - image: cimg/base:2021.01
    environment:
      TZ: "JST-9"
    steps:
      - run:
          name: no_job_execution
          command: |
            echo "------------ Job execution is skipped"

workflows:
  version: 2.1
  test-ci-release_us:
    when: << pipeline.parameters.test-ci-release_us >>
    jobs:
      - execute_shell_script:
          rel: "us"
          file: "./rel/us/rel.txt"
      - execute_update_script
  test-ci-release_jp:
    when: << pipeline.parameters.test-ci-release_jp >>
    jobs:
      - execute_shell_script:
          rel: "jp"
          file: "./rel/jp/rel.txt"
      - execute_update_script

  no_job_execution:
      when:
        and:
          - not: << pipeline.parameters.test-ci-release_us >>
          - not: << pipeline.parameters.test-ci-release_jp >>
      jobs:
        - no_job_execution
