version: 2.1
orbs:
  python: circleci/python@2.1.1
  path-filtering: circleci/path-filtering@0.0.2

## define 
parameters:
  test-ci-release_us:
    type: boolean
    default: false
  test-ci-release_jp:
    type: boolean
    default: false

executors:
  default:
    docker:
      - image: cimg/python:3.11
    environment:
      TZ: "JST-9"

jobs:
  execute_check:
    parameters:
      rel:
        type: string
        default: ""
      file:
        type: string
        default: ""
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: execute_script
          command: |
            set -x
            echo Hello, World!
            rel="<< parameters.rel >>"
            file="<< parameters.file >>"
            echo rel=${rel} file=${file}
            pwd
            env
            uname -a
            lsb_release -a
            id
            git branch
            git status
            git diff --name-only origin/main
            pip3 install ruamel.yaml
            python3 --version
            pip3 list
            which jq

  execute_pr:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: execute_update_script
          command: |
            set -x
            echo update script
            pip3 install ruamel.yaml
            GIT_USER="newtechd-kras"
            echo $GIT_TOKEN
            BRANCH_NAME="release-test"
            REPO_NAME="test-ci-release"
            git config --global user.email "kras@newtechd.com"
            git config --global user.name "Yasunari Inoue"
            git clone https://$GIT_USER:$GIT_TOKEN@github.com/newtechd-kras/$REPO_NAME.git
            cd $REPO_NAME
            git checkout -b $BRANCH_NAME
            # git checkout -b $BRANCH_NAME origin/new_branch
            cp ../test-ci/rel/jp/rel.txt .
            git add .
            git commit -m "add"
            git push origin $BRANCH_NAME

  #
  no_job_execution:
    docker:
      - image: cimg/base:2021.01
    environment:
      TZ: "JST-9"
    steps:
      - run:
          name: no_job_execution
          command: |
            echo "------------ Job execution is skipped"

workflows:
  version: 2.1
  test-ci-release_us:
    when: << pipeline.parameters.test-ci-release_us >>
    jobs:
      - execute_check:
          rel: "us"
          file: "./rel/us/rel.txt"
      - execute_pr:
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /.*/
          # branches:
          #   only: main
          requires:
            - execute_check
  test-ci-release_jp:
    when: << pipeline.parameters.test-ci-release_jp >>
    jobs:
      - execute_check:
          rel: "jp"
          file: "./rel/jp/rel.txt"
      - execute_pr:
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /.*/
          # branches:
          #   only: main
          requires:
            - execute_check

  no_job_execution:
      when:
        and:
          - not: << pipeline.parameters.test-ci-release_us >>
          - not: << pipeline.parameters.test-ci-release_jp >>
      jobs:
        - no_job_execution
